apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elk-ingress-dir
  annotations:
    nginx.org/rewrites: "serviceName=kibana rewrite=/app/kibana"
spec:
  rules:
  - host: elk.kuber.esb.kernel.local
    http:
      paths:
      - path: /elk/
        backend:
          serviceName: kibana
          servicePort: 5601
