apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-conf
spec:
  capacity:
    storage: "{{.Values.nfsconf.capacity.storage}}"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: |-
    {{- range .Values.nfsconf.nfs}}
    - {{ . }}
    {{- end}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-car
spec:
  capacity:
    storage:  "{{.Values.nfscarbon.capacity.storage}}"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: |-
    {{- range .Values.nfsconf.nfs}}
    - {{ . }}
    {{- end}}
