apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-tc-server-datadir
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "pv-tc-server-datadir"
  resources:
    requests:
      storage: 40G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-tc-server-logs
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "pv-tc-server-logs"
  resources:
    requests:
      storage: 4G