apiVersion: v1
kind: Service
metadata:
  name: tc-server-service
spec:
  sessionAffinity: ClientIP
  selector:
    app: tc-server
#   app: ws02ei

  type: NodePort
  externalIPs:
  - 10.1.158.171
  ports:
  - name: tc-web
    port: 8111
    targetPort: 8111
    protocol: TCP
 
