apiVersion: v1
kind: Pod
metadata:
  name: teamcity-server
  labels:
    app: tc-server
  
spec:
# terminationGracePeriodSeconds: 10
  volumes:
  - name: datadir
    hostPath:
      path: /opt/teamcity_server/datadir
      type: DirectoryOrCreate
  - name: logg
    hostPath:
      path: /opt/teamcity_server/logs
      type: DirectoryOrCreate
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kub04
  containers:
  - name: teamcity-server
    image: jetbrains/teamcity-server:2017.2.4
    resources:
      requests:
        cpu: "1000m"
        memory: "512Mi"
      limits:
        cpu: "2000m"
        memory: "2024Mi"
    ports:
    - containerPort: 8111
    volumeMounts:
    - name: datadir
      mountPath: /data/teamcity_server/datadir
    - name: logg
      mountPath: /opt/teamcity/logs
---
apiVersion: v1
kind: Pod
metadata:
  name: teamcity-agent
  labels:
    app: tc-client
spec:
#  terminationGracePeriodSeconds: 10
  volumes:
  - name: conf
    hostPath:
      path: /opt/teamcity_agent/conf
      type: Directory
  - name: docker
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kub04
  containers:
  - name: teamcity-agent
    image: jetbrains/teamcity-agent:2017.2.4
    env: 
    - name: SERVER_URL
      value: "10.1.158.174:8111"
    resources:
      requests:
        cpu: "512m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"
    ports:
    - containerPort: 8111
    volumeMounts:
    - name: conf
      mountPath: "/data/teamcity_agent/conf"
    - name: docker
      mountPath: "/var/run/docker.sock"

