kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-es-data-0
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/opt/disk1/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-es-data-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: "storage-es-data-0"
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-es-data-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/opt/disk1/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-es-data-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: "storage-es-data-1"
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-es-data-2
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/opt/disk2/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-es-data-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: "storage-es-data-2"
  resources:
    requests:
      storage: 10Gi
