kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-es-data-0
  labels:
    type: local
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/es-data-0/data
    server: 10.1.158.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-es-data-0
spec:
  accessModes:
    - ReadWriteMany
  volumeName: "storage-es-data-0"
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-es-data-1
  labels:
    type: local
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/es-data-1/data
    server: 10.1.158.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-es-data-1
spec:
  accessModes:
    - ReadWriteMany
  volumeName: "storage-es-data-1"
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-es-data-2
  labels:
    type: local
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/es-data-2/data
    server: 10.1.158.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-es-data-2
spec:
  accessModes:
    - ReadWriteMany
  volumeName: "storage-es-data-2"
  resources:
    requests:
      storage: 100Gi
