---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  labels:
    app: nginx-errors
spec:
  selector:
    app: nginx-errors
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1beta2
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: nginx-errors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-errors
  template:
    metadata:
      labels:
        app: nginx-errors
    spec:
      containers:
      - name: nginx-error-server
        image: quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.3
        ports:
        - containerPort: 8080
        # Setting the environment variable DEBUG we can see the headers sent 
        # by the ingress controller to the backend in the client response.
        # env:
        # - name: DEBUG
        #   value: "true"
