apiVersion: v1
kind: Service
metadata:
  "labels": {
    "apps" : "nginx",
    "env" : "devops"
  }
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  externalIPs:
  - 10.1.158.171
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress