apiVersion: v1
kind: Service
metadata:
  name: kibana-services
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  type: NodePort
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
