apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.0
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 5000
          protocol: UDP
        - containerPort: 5044
          protocol: TCP
        - containerPort: 5080
          protocol: TCP
        env:
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config-volume
        configMap:
          name: logging-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logging-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  ports:
  - name: servlet-beats
    port: 5044
    targetPort: 5044
    protocol: TCP
  - name: servlet-tcp
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: servlet-udp
    port: 5000
    targetPort: 5000
    protocol: UDP
  - name: servlet-http
    port: 5080
    targetPort: 5080
    protocol: TCP
  type: NodePort
  externalIPs:
  - 10.1.158.171
