apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  externalIPs:
  - 10.1.158.171
  ports:
  - name: http
    port: 80
    nodePort: 80
    targetPort: 8180
    protocol: TCP
  - name: https
    port: 443
    nodePort: 443
    targetPort: 8143
    protocol: TCP
  selector:
    app: ingress-nginx
